// Contactos adicionales para completar 10+ por departamento
import { guardarContacto, type ContactoDepartamento } from './contactosDepartamentoStorage';

export function inicializarContactosAdicionales(): void {
  const contactosAdicionales: Omit<ContactoDepartamento, 'id'>[] = [
    // DEPARTAMENTO 2: COMPTOIR - 7 contactos adicionales más (23-32)
    {
      departamentoId: '2',
      tipo: 'responsable-sante',
      nombre: 'Julie',
      apellido: 'Marchand',
      fechaNacimiento: '1984-08-19',
      fechaInicio: '2020-03-15',
      genero: 'Femme',
      email: 'julie.marchand@banquealimentaire.ca',
      telefono: '(514) 555-0301',
      cargo: 'Coordinatrice',
      idiomas: ['fr', 'en'],
      heuresSemaines: 37,
      reference: 'COM-001',
      direccion: '2345 Rue Rachel Est, Montréal',
      ciudad: 'Montréal',
      codigoPostal: 'H2H 1P7',
      fechaConfirmacionCasier: '2024-01-12',
      codigoEthiqueSigne: true,
      tareas: ['accueil', 'comptoir', 'admin'],
      disponibilidades: [
        { jour: 'Lundi', am: true, pm: true },
        { jour: 'Mardi', am: true, pm: true },
        { jour: 'Mercredi', am: true, pm: true },
        { jour: 'Jeudi', am: true, pm: true },
        { jour: 'Vendredi', am: true, pm: false },
        { jour: 'Samedi', am: false, pm: false },
        { jour: 'Dimanche', am: false, pm: false }
      ],
      notas: 'Supervise l\'accueil et le service aux bénéficiaires. Formation en travail social.',
      activo: true,
      fechaIngreso: '2020-03-15'
    },
    {
      departamentoId: '2',
      tipo: 'benevole',
      nombre: 'Hassan',
      apellido: 'Khalil',
      fechaNacimiento: '1990-02-28',
      fechaInicio: '2023-11-01',
      genero: 'Homme',
      email: 'hassan.khalil@email.com',
      telefono: '(514) 555-0302',
      cargo: 'Bénévole',
      idiomas: ['fr', 'ar', 'en'],
      heuresSemaines: 12,
      reference: 'BEN-098',
      direccion: '4567 Avenue du Mont-Royal, Montréal',
      ciudad: 'Montréal',
      codigoPostal: 'H2J 1X2',
      fechaConfirmacionCasier: '2023-10-25',
      codigoEthiqueSigne: true,
      tareas: ['accueil', 'comptoir'],
      disponibilidades: [
        { jour: 'Lundi', am: false, pm: false },
        { jour: 'Mardi', am: false, pm: true },
        { jour: 'Mercredi', am: false, pm: false },
        { jour: 'Jeudi', am: false, pm: true },
        { jour: 'Vendredi', am: false, pm: false },
        { jour: 'Samedi', am: false, pm: false },
        { jour: 'Dimanche', am: false, pm: false }
      ],
      notas: 'Trilingue. Excellent pour communiquer avec la communauté arabe.',
      activo: true,
      fechaIngreso: '2023-11-01'
    },
    {
      departamentoId: '2',
      tipo: 'benevole',
      nombre: 'Chantal',
      apellido: 'Girard',
      fechaNacimiento: '1972-05-14',
      fechaInicio: '2022-09-12',
      genero: 'Femme',
      email: 'chantal.girard@email.com',
      telefono: '(514) 555-0303',
      cargo: 'Bénévole',
      idiomas: ['fr'],
      heuresSemaines: 15,
      reference: 'BEN-082',
      direccion: '7890 Rue Saint-Hubert, Montréal',
      ciudad: 'Montréal',
      codigoPostal: 'H2R 2N6',
      fechaConfirmacionCasier: '2022-09-01',
      codigoEthiqueSigne: true,
      tareas: ['comptoir', 'distribution'],
      disponibilidades: [
        { jour: 'Lundi', am: true, pm: false },
        { jour: 'Mardi', am: false, pm: false },
        { jour: 'Mercredi', am: true, pm: false },
        { jour: 'Jeudi', am: false, pm: false },
        { jour: 'Vendredi', am: true, pm: false },
        { jour: 'Samedi', am: false, pm: false },
        { jour: 'Dimanche', am: false, pm: false }
      ],
      notas: 'Retraitée très engagée. Aide à la préparation des paniers alimentaires.',
      activo: true,
      fechaIngreso: '2022-09-12'
    },
    {
      departamentoId: '2',
      tipo: 'responsable-sante',
      nombre: 'David',
      apellido: 'Nguyen',
      fechaNacimiento: '1988-11-30',
      fechaInicio: '2021-06-01',
      genero: 'Homme',
      email: 'david.nguyen@banquealimentaire.ca',
      telefono: '(514) 555-0304',
      cargo: 'Travailleur social',
      idiomas: ['fr', 'en'],
      heuresSemaines: 32,
      reference: 'COM-003',
      direccion: '1234 Boulevard René-Lévesque, Montréal',
      ciudad: 'Montréal',
      codigoPostal: 'H3B 5K1',
      fechaConfirmacionCasier: '2024-01-18',
      codigoEthiqueSigne: true,
      tareas: ['accueil', 'admin'],
      disponibilidades: [
        { jour: 'Lundi', am: false, pm: true },
        { jour: 'Mardi', am: false, pm: true },
        { jour: 'Mercredi', am: false, pm: true },
        { jour: 'Jeudi', am: false, pm: true },
        { jour: 'Vendredi', am: false, pm: true },
        { jour: 'Samedi', am: false, pm: false },
        { jour: 'Dimanche', am: false, pm: false }
      ],
      notas: 'Offre soutien et orientation aux bénéficiaires. Maîtrise en travail social.',
      activo: true,
      fechaIngreso: '2021-06-01'
    },
    {
      departamentoId: '2',
      tipo: 'benevole',
      nombre: 'Monique',
      apellido: 'Lapierre',
      fechaNacimiento: '1955-09-07',
      fechaInicio: '2018-04-20',
      genero: 'Femme',
      email: 'monique.lapierre@email.com',
      telefono: '(514) 555-0305',
      cargo: 'Bénévole',
      idiomas: ['fr', 'en'],
      heuresSemaines: 20,
      reference: 'BEN-015',
      direccion: '5678 Avenue Christophe-Colomb, Montréal',
      ciudad: 'Montréal',
      codigoPostal: 'H2J 3G5',
      fechaConfirmacionCasier: '2023-11-10',
      codigoEthiqueSigne: true,
      tareas: ['accueil', 'comptoir'],
      disponibilidades: [
        { jour: 'Lundi', am: true, pm: true },
        { jour: 'Mardi', am: true, pm: true },
        { jour: 'Mercredi', am: true, pm: true },
        { jour: 'Jeudi', am: false, pm: false },
        { jour: 'Vendredi', am: false, pm: false },
        { jour: 'Samedi', am: false, pm: false },
        { jour: 'Dimanche', am: false, pm: false }
      ],
      notas: 'Bénévole depuis 6 ans. Connue et respectée par les bénéficiaires.',
      activo: true,
      fechaIngreso: '2018-04-20'
    },
    {
      departamentoId: '2',
      tipo: 'benevole',
      nombre: 'Youssef',
      apellido: 'Bouazizi',
      fechaNacimiento: '1985-01-12',
      fechaInicio: '2023-05-15',
      genero: 'Homme',
      email: 'youssef.bouazizi@email.com',
      telefono: '(514) 555-0306',
      cargo: 'Bénévole',
      idiomas: ['fr', 'ar'],
      heuresSemaines: 10,
      reference: 'BEN-093',
      direccion: '8901 Rue Jean-Talon Ouest, Montréal',
      ciudad: 'Montréal',
      codigoPostal: 'H4P 1W9',
      fechaConfirmacionCasier: '2023-05-05',
      codigoEthiqueSigne: true,
      tareas: ['accueil'],
      disponibilidades: [
        { jour: 'Lundi', am: false, pm: false },
        { jour: 'Mardi', am: false, pm: false },
        { jour: 'Mercredi', am: false, pm: true },
        { jour: 'Jeudi', am: false, pm: false },
        { jour: 'Vendredi', am: false, pm: true },
        { jour: 'Samedi', am: false, pm: false },
        { jour: 'Dimanche', am: false, pm: false }
      ],
      notas: 'Professeur de français. Aide à la traduction pour les nouveaux arrivants.',
      activo: true,
      fechaIngreso: '2023-05-15'
    },
    {
      departamentoId: '2',
      tipo: 'partenaire',
      nombre: 'Louise',
      apellido: 'Dumas',
      fechaNacimiento: '1980-03-25',
      genero: 'Femme',
      email: 'louise.dumas@nutritionsante.ca',
      telefono: '(514) 555-0307',
      cargo: 'Nutritionniste',
      idiomas: ['fr', 'en'],
      reference: 'PAR-012',
      direccion: '3456 Chemin Queen-Mary, Montréal',
      ciudad: 'Montréal',
      codigoPostal: 'H3V 1A5',
      notas: 'Consultations nutritionnelles gratuites le jeudi après-midi.',
      activo: true,
      fechaIngreso: '2021-09-10'
    }
  ];

  // Guardar todos los contactos adicionales
  contactosAdicionales.forEach(contacto => {
    guardarContacto(contacto);
  });
}
