import { ProductoCreado, guardarProducto, obtenerProductos } from './productStorage';

/**
 * Crear productos de ejemplo para el sistema
 * Estos productos servirán como base para las conversiones
 */
export function crearProductosEjemplo() {
  const productosExistentes = obtenerProductos();
  
  // Si ya hay productos, no crear ejemplos
  if (productosExistentes.length > 0) {
    console.log('Ya existen productos en el sistema');
    return;
  }

  const fechaActual = new Date().toISOString().split('T')[0];
  const fechaVencimiento = new Date();
  fechaVencimiento.setMonth(fechaVencimiento.getMonth() + 6);
  const fechaVencimientoStr = fechaVencimiento.toISOString().split('T')[0];

  const productosEjemplo: ProductoCreado[] = [
    // CEREALES - Diferentes tamaños
    {
      id: 'prod-cereal-2kg',
      codigo: 'CER-001',
      nombre: 'Céréales (Boîte 2kg)',
      categoria: 'Aliments Secs',
      subcategoria: 'Céréales',
      unidad: 'boîtes',
      icono: '🥣',
      peso: 2.0,
      pesoUnitario: 2.0,
      stockActual: 50,
      stockMinimo: 10,
      ubicacion: 'A1',
      lote: 'LOT-2025-001',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-cereal-3kg',
      codigo: 'CER-002',
      nombre: 'Céréales (Boîte 3kg)',
      categoria: 'Aliments Secs',
      subcategoria: 'Céréales',
      unidad: 'boîtes',
      icono: '🥣',
      peso: 3.0,
      pesoUnitario: 3.0,
      stockActual: 0,
      stockMinimo: 10,
      ubicacion: 'A1',
      lote: 'LOT-2025-002',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-cereal-500g',
      codigo: 'CER-003',
      nombre: 'Céréales (Paquet 500g)',
      categoria: 'Aliments Secs',
      subcategoria: 'Céréales',
      unidad: 'paquets',
      icono: '🥣',
      peso: 0.5,
      pesoUnitario: 0.5,
      stockActual: 0,
      stockMinimo: 20,
      ubicacion: 'A1',
      lote: 'LOT-2025-003',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },

    // FRUTAS - Variadas y específicas
    {
      id: 'prod-frutas-variadas',
      codigo: 'FRU-001',
      nombre: 'Fruits Variés (PRS)',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Fruits',
      unidad: 'kg',
      icono: '🍎',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 150,
      stockMinimo: 20,
      ubicacion: 'B3',
      lote: 'PRS-2025-001',
      fechaVencimiento: fechaActual,
      esPRS: true,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-manzanas',
      codigo: 'FRU-002',
      nombre: 'Pommes',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Fruits',
      unidad: 'kg',
      icono: '🍎',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 30,
      ubicacion: 'B3',
      lote: 'FRU-2025-001',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-bananas',
      codigo: 'FRU-003',
      nombre: 'Bananes',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Fruits',
      unidad: 'kg',
      icono: '🍌',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 25,
      ubicacion: 'B3',
      lote: 'FRU-2025-002',
      fechaVencimiento: fechaActual,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-naranjas',
      codigo: 'FRU-004',
      nombre: 'Oranges',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Fruits',
      unidad: 'kg',
      icono: '🍊',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 25,
      ubicacion: 'B3',
      lote: 'FRU-2025-003',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },

    // VERDURAS - Variadas y específicas
    {
      id: 'prod-verduras-variadas',
      codigo: 'LEG-001',
      nombre: 'Légumes Variés (PRS)',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Légumes',
      unidad: 'kg',
      icono: '🥬',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 200,
      stockMinimo: 30,
      ubicacion: 'B4',
      lote: 'PRS-2025-002',
      fechaVencimiento: fechaActual,
      esPRS: true,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-zanahorias',
      codigo: 'LEG-002',
      nombre: 'Carottes',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Légumes',
      unidad: 'kg',
      icono: '🥕',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 40,
      ubicacion: 'B4',
      lote: 'LEG-2025-001',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-papas',
      codigo: 'LEG-003',
      nombre: 'Pommes de terre',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Légumes',
      unidad: 'kg',
      icono: '🥔',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 50,
      ubicacion: 'B4',
      lote: 'LEG-2025-002',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-brocoli',
      codigo: 'LEG-004',
      nombre: 'Brocoli',
      categoria: 'Fruits et Légumes',
      subcategoria: 'Légumes',
      unidad: 'kg',
      icono: '🥦',
      peso: 0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 20,
      ubicacion: 'B4',
      lote: 'LEG-2025-003',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },

    // ARROZ - Diferentes tamaños
    {
      id: 'prod-arroz-25kg',
      codigo: 'ARR-001',
      nombre: 'Riz (Sac 25kg)',
      categoria: 'Aliments Secs',
      subcategoria: 'Riz et Grains',
      unidad: 'sacs',
      icono: '🍚',
      peso: 25.0,
      pesoUnitario: 25.0,
      stockActual: 20,
      stockMinimo: 5,
      ubicacion: 'A2',
      lote: 'ARR-2025-001',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-arroz-1kg',
      codigo: 'ARR-002',
      nombre: 'Riz (Paquet 1kg)',
      categoria: 'Aliments Secs',
      subcategoria: 'Riz et Grains',
      unidad: 'paquets',
      icono: '🍚',
      peso: 1.0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 50,
      ubicacion: 'A2',
      lote: 'ARR-2025-002',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },

    // PASTA - Diferentes tamaños
    {
      id: 'prod-pasta-5kg',
      codigo: 'PAS-001',
      nombre: 'Pâtes (Sac 5kg)',
      categoria: 'Aliments Secs',
      subcategoria: 'Pâtes',
      unidad: 'sacs',
      icono: '🍝',
      peso: 5.0,
      pesoUnitario: 5.0,
      stockActual: 30,
      stockMinimo: 10,
      ubicacion: 'A3',
      lote: 'PAS-2025-001',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-pasta-500g',
      codigo: 'PAS-002',
      nombre: 'Pâtes (Paquet 500g)',
      categoria: 'Aliments Secs',
      subcategoria: 'Pâtes',
      unidad: 'paquets',
      icono: '🍝',
      peso: 0.5,
      pesoUnitario: 0.5,
      stockActual: 0,
      stockMinimo: 100,
      ubicacion: 'A3',
      lote: 'PAS-2025-002',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },

    // CONSERVAS - Variadas y específicas
    {
      id: 'prod-conservas-variadas',
      codigo: 'CON-001',
      nombre: 'Conserves Variées',
      categoria: 'Conserves',
      subcategoria: 'Conserves Mixtes',
      unidad: 'boîtes',
      icono: '🥫',
      peso: 0.4,
      pesoUnitario: 0.4,
      stockActual: 80,
      stockMinimo: 20,
      ubicacion: 'C1',
      lote: 'CON-2025-001',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-conserva-tomate',
      codigo: 'CON-002',
      nombre: 'Conserve de Tomate',
      categoria: 'Conserves',
      subcategoria: 'Conserves de Légumes',
      unidad: 'boîtes',
      icono: '🍅',
      peso: 0.4,
      pesoUnitario: 0.4,
      stockActual: 0,
      stockMinimo: 30,
      ubicacion: 'C1',
      lote: 'CON-2025-002',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-conserva-mais',
      codigo: 'CON-003',
      nombre: 'Conserve de Maïs',
      categoria: 'Conserves',
      subcategoria: 'Conserves de Légumes',
      unidad: 'boîtes',
      icono: '🌽',
      peso: 0.4,
      pesoUnitario: 0.4,
      stockActual: 0,
      stockMinimo: 30,
      ubicacion: 'C1',
      lote: 'CON-2025-003',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-conserva-haricots',
      codigo: 'CON-004',
      nombre: 'Conserve de Haricots',
      categoria: 'Conserves',
      subcategoria: 'Conserves de Légumineuses',
      unidad: 'boîtes',
      icono: '🫘',
      peso: 0.4,
      pesoUnitario: 0.4,
      stockActual: 0,
      stockMinimo: 25,
      ubicacion: 'C1',
      lote: 'CON-2025-004',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },

    // LECHE EN POLVO - Diferentes tamaños
    {
      id: 'prod-leche-25kg',
      codigo: 'LAI-001',
      nombre: 'Lait en poudre (Sac 25kg)',
      categoria: 'Produits Laitiers',
      subcategoria: 'Lait',
      unidad: 'sacs',
      icono: '🥛',
      peso: 25.0,
      pesoUnitario: 25.0,
      stockActual: 10,
      stockMinimo: 3,
      ubicacion: 'D1',
      lote: 'LAI-2025-001',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    },
    {
      id: 'prod-leche-1kg',
      codigo: 'LAI-002',
      nombre: 'Lait en poudre (Paquet 1kg)',
      categoria: 'Produits Laitiers',
      subcategoria: 'Lait',
      unidad: 'paquets',
      icono: '🥛',
      peso: 1.0,
      pesoUnitario: 1.0,
      stockActual: 0,
      stockMinimo: 40,
      ubicacion: 'D1',
      lote: 'LAI-2025-002',
      fechaVencimiento: fechaVencimientoStr,
      esPRS: false,
      activo: true,
      fechaCreacion: fechaActual
    }
  ];

  // Guardar cada producto
  productosEjemplo.forEach(producto => {
    guardarProducto(producto);
  });

  console.log(`✅ ${productosEjemplo.length} produits d'exemple créés avec succès`);
}
