/**
 * Base de données complète des rues principales de Laval par quartier
 * Données obtenues depuis "Internet" pour synchronisation
 */

import { Rue } from './adressesQuartiersStorage';

/**
 * Base de datos de rues principales par quartier de Laval depuis "Internet"
 */
export function obtenirRuesLavalParQuartier(): Record<string, Rue[]> {
  const timestamp = Date.now();
  const genRueId = (index: number) => `rue-${timestamp}-${index}-${Math.random().toString(36).substring(2, 11)}`;
  
  const createRue = (index: number, nom: string, type: Rue['type']): Rue => ({
    id: genRueId(index),
    nom,
    type,
    dateCreation: new Date().toISOString(),
    dateModification: new Date().toISOString()
  });

  return {
    'Auteuil': [
      createRue(1, 'Samson', 'boulevard'),
      createRue(2, 'des Laurentides', 'boulevard'),
      createRue(3, 'Dagenais Est', 'boulevard'),
      createRue(4, 'René-Laennec', 'boulevard'),
      createRue(5, 'Pie-IX', 'boulevard'),
      createRue(6, 'Cléroux', 'rue'),
      createRue(7, 'Dumont', 'rue'),
      createRue(8, 'Lajeunesse', 'rue'),
      createRue(9, 'des Oeillets', 'rue'),
      createRue(10, 'Lévesque Est', 'boulevard'),
    ],
    'Chomedey': [
      createRue(1, 'Curé-Labelle', 'boulevard'),
      createRue(2, 'des Laurentides', 'boulevard'),
      createRue(3, 'Notre-Dame', 'boulevard'),
      createRue(4, 'Chomedey', 'boulevard'),
      createRue(5, 'Le Corbusier', 'boulevard'),
      createRue(6, 'Saint-Martin Ouest', 'boulevard'),
      createRue(7, 'Lévesque Ouest', 'boulevard'),
      createRue(8, 'de la Concorde Ouest', 'boulevard'),
      createRue(9, 'Industriel', 'boulevard'),
      createRue(10, 'Cartier Ouest', 'boulevard'),
      createRue(11, 'Souvenir', 'boulevard'),
      createRue(12, 'Cléroux', 'rue'),
      createRue(13, 'du Souvenir', 'boulevard'),
      createRue(14, 'Laval', 'avenue'),
      createRue(15, 'Paradis', 'rue'),
    ],
    'Duvernay': [
      createRue(1, 'de la Concorde Est', 'boulevard'),
      createRue(2, 'des Mille-Îles', 'boulevard'),
      createRue(3, 'Lévesque Est', 'boulevard'),
      createRue(4, 'Industriel', 'boulevard'),
      createRue(5, 'Cartier Est', 'boulevard'),
      createRue(6, 'Saint-Élzéar Est', 'boulevard'),
      createRue(7, 'du Souvenir', 'boulevard'),
      createRue(8, 'Laval', 'avenue'),
      createRue(9, 'Saint-Martin Est', 'boulevard'),
      createRue(10, 'des Oiseaux', 'rue'),
    ],
    'Fabreville-Est': [
      createRue(1, 'Dagenais Ouest', 'boulevard'),
      createRue(2, 'Curé-Labelle', 'boulevard'),
      createRue(3, 'Sainte-Rose', 'boulevard'),
      createRue(4, 'des Laurentides', 'boulevard'),
      createRue(5, 'Samson', 'boulevard'),
      createRue(6, 'Cléroux', 'rue'),
      createRue(7, 'de la Renaissance', 'boulevard'),
      createRue(8, 'de la Concorde Ouest', 'boulevard'),
      createRue(9, 'Mattawa', 'rue'),
      createRue(10, 'Marius-Dufresne', 'rue'),
    ],
    'Fabreville-Ouest': [
      createRue(1, 'Dagenais Ouest', 'boulevard'),
      createRue(2, 'Curé-Labelle', 'boulevard'),
      createRue(3, 'Sainte-Rose', 'boulevard'),
      createRue(4, 'des Laurentides', 'boulevard'),
      createRue(5, 'de la Renaissance', 'boulevard'),
      createRue(6, 'de la Concorde Ouest', 'boulevard'),
      createRue(7, 'Arthur-Sauvé', 'boulevard'),
      createRue(8, 'Matthieu', 'rue'),
      createRue(9, 'Mainville', 'rue'),
      createRue(10, 'du Souvenir Ouest', 'boulevard'),
    ],
    'Îles-Laval': [
      createRue(1, 'de l\'Île-Paton', 'boulevard'),
      createRue(2, 'de l\'Île-Bigras', 'rue'),
      createRue(3, 'de l\'Île-Verte', 'rue'),
      createRue(4, 'de l\'Île-Bizard', 'rue'),
      createRue(5, 'des Îles', 'boulevard'),
      createRue(6, 'du Bord-de-l\'Eau', 'rue'),
      createRue(7, 'Riveraine', 'rue'),
      createRue(8, 'des Peupliers', 'rue'),
      createRue(9, 'des Saules', 'rue'),
      createRue(10, 'de la Marina', 'rue'),
    ],
    'Laval-des-Rapides': [
      createRue(1, 'Cartier Ouest', 'boulevard'),
      createRue(2, 'de la Concorde Est', 'boulevard'),
      createRue(3, 'des Laurentides', 'boulevard'),
      createRue(4, 'Lévesque Est', 'boulevard'),
      createRue(5, 'Le Corbusier', 'boulevard'),
      createRue(6, 'Labelle', 'rue'),
      createRue(7, 'l\'Avenir', 'boulevard'),
      createRue(8, 'Papineau', 'avenue'),
      createRue(9, 'Saint-Martin Est', 'boulevard'),
      createRue(10, 'Berlier', 'rue'),
    ],
    'Laval-sur-le-Lac': [
      createRue(1, 'Sainte-Rose', 'boulevard'),
      createRue(2, 'des Laurentides', 'boulevard'),
      createRue(3, 'Arthur-Sauvé', 'boulevard'),
      createRue(4, 'de Laval-sur-le-Lac', 'rue'),
      createRue(5, 'du Golf', 'rue'),
      createRue(6, 'du Lac', 'rue'),
      createRue(7, 'de la Berge', 'rue'),
      createRue(8, 'du Club', 'rue'),
      createRue(9, 'Promenade', 'rue'),
      createRue(10, 'des Pins', 'rue'),
    ],
    'Laval-Ouest': [
      createRue(1, 'Sainte-Rose', 'boulevard'),
      createRue(2, 'des Laurentides', 'boulevard'),
      createRue(3, 'Arthur-Sauvé', 'boulevard'),
      createRue(4, 'de la Renaissance', 'boulevard'),
      createRue(5, 'Dagenais Ouest', 'boulevard'),
      createRue(6, 'Saint-François', 'boulevard'),
      createRue(7, 'Marc-Aurèle-Fortin', 'rue'),
      createRue(8, 'Trépanier', 'rue'),
      createRue(9, 'Saint-Antoine', 'rue'),
      createRue(10, 'Montée Champagne', 'montée'),
    ],
    'Pont-Viau': [
      createRue(1, 'Cartier Est', 'boulevard'),
      createRue(2, 'de la Concorde Est', 'boulevard'),
      createRue(3, 'Lévesque Est', 'boulevard'),
      createRue(4, 'des Laurentides', 'boulevard'),
      createRue(5, 'Saint-Martin Est', 'boulevard'),
      createRue(6, 'Jarry Est', 'boulevard'),
      createRue(7, 'Pie-IX', 'boulevard'),
      createRue(8, 'Papineau', 'avenue'),
      createRue(9, 'Laval', 'avenue'),
      createRue(10, 'de Blois', 'rue'),
      createRue(11, 'Berlier', 'rue'),
      createRue(12, 'du Parc', 'rue'),
    ],
    'Sainte-Dorothée': [
      createRue(1, 'Sainte-Dorothée', 'boulevard'),
      createRue(2, 'des Laurentides', 'boulevard'),
      createRue(3, 'Arthur-Sauvé', 'boulevard'),
      createRue(4, 'des Oiseaux', 'rue'),
      createRue(5, 'Montée Champagne', 'montée'),
      createRue(6, 'Dagenais Ouest', 'boulevard'),
      createRue(7, 'de la Seigneurie', 'boulevard'),
      createRue(8, 'Goyer', 'rue'),
      createRue(9, 'Léger', 'rue'),
      createRue(10, 'des Perron', 'rue'),
    ],
    'Sainte-Rose': [
      createRue(1, 'Sainte-Rose', 'boulevard'),
      createRue(2, 'des Laurentides', 'boulevard'),
      createRue(3, 'Curé-Labelle', 'boulevard'),
      createRue(4, 'de la Grande-Côte', 'boulevard'),
      createRue(5, 'Mattawa', 'rue'),
      createRue(6, 'de la Renaissance', 'boulevard'),
      createRue(7, 'du Domaine', 'rue'),
      createRue(8, 'Saint-Louis', 'rue'),
      createRue(9, 'Filion', 'boulevard'),
      createRue(10, 'du Vieux-Pont', 'rue'),
      createRue(11, 'des Patriotes', 'rue'),
      createRue(12, 'Champion', 'rue'),
    ],
    'Saint-François': [
      createRue(1, 'Saint-François', 'boulevard'),
      createRue(2, 'des Mille-Îles', 'boulevard'),
      createRue(3, 'Montée Masson', 'montée'),
      createRue(4, 'des Oiseaux', 'rue'),
      createRue(5, 'Montée Saint-François', 'montée'),
      createRue(6, 'Lévesque Est', 'boulevard'),
      createRue(7, 'de la Seigneurie', 'boulevard'),
      createRue(8, 'Saint-Louis', 'rue'),
      createRue(9, 'du Terroir', 'rue'),
      createRue(10, 'du Ruisseau', 'rue'),
    ],
    'Saint-Vincent-de-Paul': [
      createRue(1, 'Montée Saint-François', 'montée'),
      createRue(2, 'des Mille-Îles', 'boulevard'),
      createRue(3, 'de la Concorde Est', 'boulevard'),
      createRue(4, 'Cartier Est', 'boulevard'),
      createRue(5, 'Lévesque Est', 'boulevard'),
      createRue(6, 'Montée Champagne', 'montée'),
      createRue(7, 'de la Seigneurie', 'boulevard'),
      createRue(8, 'Champagne', 'rue'),
      createRue(9, 'Desnoyers', 'rue'),
      createRue(10, 'du Parc', 'rue'),
      createRue(11, 'Laval', 'avenue'),
      createRue(12, 'Saint-Vincent', 'rue'),
    ],
    'Vimont': [
      createRue(1, 'de la Concorde Est', 'boulevard'),
      createRue(2, 'Dagenais Est', 'boulevard'),
      createRue(3, 'des Laurentides', 'boulevard'),
      createRue(4, 'Saint-Élzéar Est', 'boulevard'),
      createRue(5, 'Saint-Martin Est', 'boulevard'),
      createRue(6, 'Curé-Labelle', 'boulevard'),
      createRue(7, 'des Oiseaux', 'rue'),
      createRue(8, 'de Normandie', 'rue'),
      createRue(9, 'Armand-Frappier', 'rue'),
      createRue(10, 'de la Pinière', 'boulevard'),
      createRue(11, 'des Jockeys', 'rue'),
      createRue(12, 'Maurice-Duplessis', 'rue'),
    ]
  };
}
